lib/sys-info.ts, package.json
When we execute `android -h` on mac the command exits with code 1. In our childProcess if a command has exit code != 0 we throw an error. It is OK to ignore the exit code for `android -h` because the command will be executed correctly and on the stdout we will have the correct output. If android is not installed there will be no data on the stdout and we will set in the sysInfo that android is not installed.
=> Fix android -h check on mac

lib/android-tools-info.ts, package.json
The method that validates ANDROID_HOME returns array with errors, so current `if(isAndroidHomeValid)` checks are always true.
Create new method that returns boolean value and use it instead.
=> Fix check isAndroidHomeValid

lib/sys-info.ts, package.json, test/sys-info.ts
When path to ANDROID_HOME contains spaces, we do not get the path to adb correctly and we return error that adb is not installed.
Fix this by using child_process.spawn which handles spaces.
Fix incorrect tests which did not consider the `ignoreError` option of spawnFromEvent method.
=> Fix getting information about adb

lib/sys-info.ts, package.json
In case ANDROID_HOME is not set, trying to get adb version leads to error. Fix this by checking the value of pathToAdbFromAndroidHome. In case it is not set, return null.
=> Fix getting adb version when ANDROID_HOME is not set 

README.md, lib/sys-info.ts, package.json, test/sys-info.ts, typings/interfaces.ts
Add command to get the version of `nativescript-cloud` library.
Fix getting the version of globally installed Node.js - we've been incorrectly using `process.version` instead of spawning `node -v`.
=> Add getting version of nativescript-cloud library

lib/sys-info.ts, package.json
In case `nativescript-cloud` lib is not installed, the spawned tns command fails and prints the result to the stdout.
So add parsing of the result and use it only when the stdout is valid version.
=> Fix getting the version of nativescript-cloud when it is not installed

lib/sys-info.ts, package.json, test/sys-info.ts
In case CLI prints other things (like warnings from loading extensions) to its stdout, the `nativescript-doctor` returns incorrect version for CLI.
Fix this by getting only the version from stdout.
Add unit tests for this scenario.
`@types/temp` depends on `"@types/node": "*"`, so a new version of the `node.d.ts` is installed. This breaks our code. Fix the code, but we'll have to figure it out how to make sure it won't happen again.
=> Fix getting CLI version

lib/sys-info.ts, package.json, test/sys-info.ts
The sysInfo spawns NativeScript CLI's commands to get CLI's version and the version of `nativescript-cloud`. However, in some cases, CLI's output contains warnings that Node.js version is not supported. These warnings contain version of Node.js and current code decides that this is the version of CLI (and nativescript-cloud). Fix the parsing by using different regular expression - in CLI's output the version is always on a new line, so rely on this.
Add unit tests for this scenario and for getting the version of nativescript-cloud.
=> Fix parsing of CLI's output

lib/android-tools-info.ts, lib/helpers.ts, lib/sys-info.ts, package.json, test/sys-info.ts
It is already used in NativeScript CLI.
In case Cocoapods version is below 1.0.0 and Xcode version contains only two digits, we fail as semver cannot work with versions with two digits.
Append zero to the version, to make it correct semver.
=> Fix some failures

README.md, lib/sys-info.ts, test/sys-info.ts, typings/interfaces.ts
Remove getting cloud lib version through spawning command as this is no longer required. CLI has API to get the installed extensions, so it should be used instead.
=> Remove getting cloud lib version

.travis.yml, README.md, lib/android-tools-info.ts, lib/constants.ts, lib/doctor.ts, lib/helpers.ts, lib/index.ts, lib/local-build-requirements/android-local-build-requirements.ts, lib/sys-info.ts, package.json, test/android-tools-info.ts, test/sys-info.ts, typings/interfaces.ts
* Add check for JAVA 9
Currently Gradle cannot work with JAVA 9, so detect if it has been used and return correct warning.
Fix detection of Javac version
The command `javac -version` prints result to stderr when JAVA 8 is used and to stdout when JAVA 9 is used. Current check uses the stderr output, so when JAVA 9 is installed it fails to detect the correct version.
In order to support both JAVA 8 and JAVA 9, capture both stdout and stderr and get the version from there.
Also remove unneeded check for Java version - we care about JAVA Compiler, which is included in JDK.
* Handle case when Javac version is a single number (9 for example)
In some cases javac version is a single number, for example 9. In this case our validation fails to detect the correct version and to check if we support …
=> Add check for JAVA 9 

lib/android-tools-info.ts
Add version 27 of Android SDK as verified, so users will use it by default when it is installed.
Use latest available appCompat version
The current logic finds appCompat version that matches the selected SDK version. However, the latest appCompat version is 26.0.0-alpha, so in case we have Android SDK 27, we are unable to find matching appCompat.
In order to resolve the issue and allow using Android SDK 27, get latest available appCompat version when there's no matching one
=> Add Android SDK 27 as verified

lib/doctor.ts
Add the check for `darwin os` at the end of doctor, so this is the last printed message when doctor command is executed.
=> Remove unneeded note message

lib/doctor.ts, lib/sys-info.ts, test/sys-info.ts, typings/interfaces.ts
In case when android platform is specified, checks only android related things. In case when iOS platform is specified, checks only iOS related things. When no platform is specified, checks both Android and iOS things. This will improve the time {N} CLI needs to check if environment is correctly configured for platform specific commands. This also will fix failing cloud builds.
=> Get sysInfos based on specified platform

README.md, lib/android-tools-info.ts, lib/constants.ts, lib/declarations.d.ts, lib/doctor.ts, lib/local-build-requirements/android-local-build-requirements.ts, lib/wrappers/child-process.ts, lib/wrappers/file-system.ts, package.json, test/android-tools-info.ts, test/sys-info.ts, typings/interfaces.ts
In NativeScript 4.1.0 we add support for Java 10. However, older versions of the Android runtime cannot work with Java 10, so verification for the current environment and local builds depends on the current Android runtime version.
In order to handle this, add projectDir parameter to the API. In case it is passed, we'll check if Android Runtime version is specified in the package.json and we'll verify if it is supported for the current Java version.
=> feat: Validate Javac version with Android runtime version

lib/android-tools-info.ts, lib/doctor.ts, lib/local-build-requirements/android-local-build-requirements.ts, lib/sys-info.ts, package.json, typings/interfaces.ts
Allow verification of the environment based on a specified Android runtime version. This is required for cases where the package.json of the project is not updated yet, but we need to verify that we can use this runtime
=> feat: Validate Java version based on passed runtime version

lib/local-build-requirements/android-local-build-requirements.ts, test/android-local-build-requirements.ts
In case there's a problem with Javac version (for example it is 10.0.0, but current project uses Android runtime, that cannot be used with this Java version), the checkRequirements method disregards the warning.
Fix the check and add tests.
=> fix: Check for Local Android build disregards issues in Javac version

lib/android-tools-info.ts, package.json, typings/interfaces.ts
In the past there was a requirement to have a local copy of the Android Support Repository in order to use it in your application.
However, since some time the new versions of the libraries are in the Google repository, so there's no need to have them locally.
=> feat: remove requirement for Android Support Repository installation

lib/constants.ts, lib/doctor.ts, lib/local-build-requirements/ios-local-build-requirements.ts, package.json, test/ios-local-build-requirements.ts
Currently iOS apps cannot be build with Xcode versions below 9, so add a check for the min supported Xcode version.
=> feat: drop support for Xcode versions below 9

lib/android-tools-info.ts, package.json
As we are going to set min required Android Support Library to be 28 (in the modules), we need to set the min required compile SDK to 28 as well (as Android Support Library 28 relies on resources included in this version of the SDK and the project cannot be build without them). This way CLI will not allow building an application without installing the Android SDK 28 first.
=> feat: set min required compile SDK to 28

lib/wrappers/file-system.ts, package.json
Sometimes the out stream is closed before receiving stream's end event. In this case "EBADF: bad file descriptor, write" error is thrown
=> fix: fix sporadic "EBADF: bad file descriptor, write" error

lib/constants.ts, lib/sys-info.ts, package-lock.json, package.json, test/sys-info.ts, typings/interfaces.ts
macOS has handle when you try to execute java or javac to prompt to install it. However, we do not want to bother the user with such prompts. Currently we are executing `javac -version` to determine the version. Instead of this, check if there's `javac` in the PATH before executing the command. In case there's no javac in the path, do not execute `javac -version`, so we'll not prompt the user to install it.
Expose methods for getting JAVA version from PATH, from JAVA_HOME and wrapper for both of them. This is required for some verifications around avdmanager executable
=> fix: prompts to install javac should not be shown on macOS

lib/sys-info.ts, package.json, test/sys-info.ts
The current `javac` detection tries to get the `javac` path from JAVA_HOME and to verify it is correct. In case it fails somewhere, it fallbacks to check the `javac` from PATH. So, from users' perspective it seems javac is setup correctly.
However, Gradle works in slightly different manner - it checks if you have JAVA_HOME and if so - verifies `java` from it. In case there's no `java` in the `$JAVA_HOME/bin/java`, an error is thrown.
Make our check for `javac` in the same way - in case you have set JAVA_HOME, we'll verify `javac` from there. This is exactly the same as the one we had prior 1.9.0 version, so this is just a regression fix.
Add unit tests to cover this scenario.
=> fix: javac detection does not work as required by Gradle

lib/constants.ts, package.json
With NativeScript 6.0.0 release we will require Xcode 10 as min supported.
=> feat: set min required Xcode version to 10

lib/android-tools-info.ts, package.json
Related to https://github.com/NativeScript/nativescript-cli/issues/4926
=> fix: runtime supports sdk 28 only and user has 29 or no sdk, doctor prints wrong message

lib/android-tools-info.ts, lib/sys-info.ts, lib/wrappers/file-system.ts, package.json, test/android-tools-info.ts
Currently Java 13 is not supported, but if you have it installed, `nativescript-doctor` decides it is okay and allows you to build. At that point you receive non-descriptive error message. Fix the case by forbidding Java 13 and above until we support it.
Ensure the temp files created by nativescript-doctor are deleted
=> fix: Java 13 is not supported, but it is not detected as such

lib/wrappers/file-system.ts
Issue:
Environment aliases are not resolved by `fs.exists` but environment variables are.
Example:
`export ANDROID_HOME=~/Library/Android/sdk` will fail
`export ANDROID_HOME=$HOME/Library/Android/sdk` will pass
Fix:
Resolve the path before testing it by wrapping it with `path.resolve()`.
Related Issue:
https://github.com/NativeScript/nativescript-cli/issues/1097
=> Resolve paths before testing for existence

lib/android-tools-info.ts, package.json, test/android-tools-info.ts, tslint.json
closes https://github.com/NativeScript/nativescript-cli/issues/5330
=> feat(android): support v30

.travis.yml, lib/wrappers/file-system.ts, test/wrappers/file-system.ts
Had to fix this to prevent this error when running tests on Windows
```
Error: EINVAL: invalid argument, mkdir 'C:\C:'
```
=> Handle file paths correctly on Windows
